package it.polimi.ingsw.view.events;

public enum EventType {
    BACK_TO_MENU,
    PLAYER_JOINED,
    GAME_FULL,
    NICKNAME_ALREADY_IN,
    GENERIC_ERROR,
    PLAYER_LEFT,
    GAME_STARTED,
    GAME_ENDED,
    NEXT_TURN,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED,
    CARD_PLACED,
    CARD_PLACED_NOT_CORRECT,
    CARD_DRAWN


}
